sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: gyq19980901
  redis:
    host: localhost
    port: 6379

  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tFdP77XDjh5x2xyMQqQ
    access-key-secret: 9RbLWG0vp7pa17JdmQH7U16FXWGHnK
    bucket-name: gyq-gulimail
  wechat:
    appid: wx69b98f386f85e020
    secret: 3bb4bce3133c3c22e02e2785d6c62dba

